version: '3'
services:
  student-service:
    build: .
#    image: mique10/student_service
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      MONGO_URI: mongodb://mongodb:27017

  mongodb:
    image: mongo:4
    restart: unless-stopped
    ports:
      - "27017:27017"